### ISSUE TITLE
Remove some of our changes

### ISSUE THREAD

**Issue by tkeemon** [appsembler/configuration#5]
These two changes:
- https://github.com/appsembler/configuration/blob/a41fb7953898829ac82a29dd747c7b7db7a67aa8/playbooks/roles/edxapp/defaults/main.yml#L18-L21
- https://github.com/appsembler/configuration/blob/a41fb7953898829ac82a29dd747c7b7db7a67aa8/playbooks/roles/edxapp/defaults/main.yml#L806

can be removed from our version of the fork if we do the following in each customer's server-vars.yml file:

```
---
EDXAPP_APPSEMBLER_FEATURES: 
  FEATURE_1: value
  FEATURE_2: value

EDXAPP_ENV_EXTRA:
  APPSEMBLER_FEATURES: "{{ EDXAPP_APPSEMBLER_FEATURES }}"
```
